// Generated by CoffeeScript 1.4.0

requirejs.config({
  'packages': ['viewport']
});

requirejs(['viewport'], function(Viewport) {
  try {
    return new Viewport;
  } catch (error) {
    return console.log(error);
  }
});
