// Generated by CoffeeScript 1.4.0
var express, host, http, io, port, viewport;

http = require('http');

express = require('express');

io = require('socket.io');

host = 'localhost';

port = 3000;

viewport = require('viewport');

module.exports = {
  start: function(root) {
    var app, server, sockets;
    app = express();
    server = http.createServer(app);
    sockets = io.listen(server);
    app.use(express.logger('dev'));
    app.use(viewport());
    app.set('views', root + '/views');
    app.set('view engine', 'jade');
    app.get('/', function(req, res) {
      return res.render('index');
    });
    return server.listen(port, host, function() {
      return console.log('http://%s:%s', server.address().address, server.address().port);
    });
  }
};
